name: "Install"
description: "Sets up Node.js and runs install"
inputs:
  target:
    description: 'the rust toolchain'
    required: true
    default: 'aarch64-apple-darwin'
runs:
  using: composite
  steps:
    - uses: actions/setup-node@v3
      with:
        node-version: 18
    - uses: actions/checkout@v4
    - name: setup node
      uses: actions/setup-node@v4
      with:
        node-version: 20
    - name: install Rust stable
      uses: dtolnay/rust-toolchain@stable
      with:
        targets: "${{ inputs.target }}"
    - uses: pnpm/action-setup@v2
      with:
        version: 8
