name: Deploy bot 

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy
    steps:
      - uses: actions/checkout@v4
      - uses: dorny/paths-filter@v3
        id: changes
        with:
          filters: |
            bot:
              - 'apps/bot/**'
      - uses: pnpm/action-setup@v3
        if: steps.changes.outputs.api == 'true' && ${{ github.event_name }}" != "workflow_dispatch"
        with:
          version: 9
      - name: Deploy commands
        run: pnpm register
        working-directory: apps/bot
        env:
          DISCORD_APPLICATION_ID: ${{ secrets.DISCORD_APPLICATION_ID }} 
          DISCORD_TOKEN: ${{ secrets.DISCORD_TOKEN }} 
      - name: Deploy worker
        if: steps.changes.outputs.api == 'true' && ${{ github.event_name }}" != "workflow_dispatch"
        uses: cloudflare/wrangler-action@v3
        with:
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          workingDirectory: apps/bot
          packageManager: pnpm
