name: "Release"
on:
  # Allow manual
  workflow_dispatch:

jobs:
  build-tauri:
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
            exe_name: overlayed 
          - os: macos-latest
            target: aarch64-apple-darwin
            exe_name: overlayed 
          - os: windows-latest
            target: x86_64-pc-windows-msvc
            exe_name: overlayed.exe
    runs-on: ${{ matrix.os }}
    steps:
      - name: Setup and install
        uses: ./github/tooling/setup
      - name: install dependencies (ubuntu only)
        if: matrix.platform == 'ubuntu-latest'
        run: |
          sudo apt-get update
          sudo apt-get install -y libgtk-3-dev libwebkit2gtk-4.0-dev libappindicator3-dev librsvg2-dev patchelf
      - uses: pnpm/action-setup@v2
        with:
          version: 8
      - name: install frontend dependencies
        run: pnpm install
      - name: build tauri app
        working-directory: apps/desktop
        run: |
          cargo tauri build
          ls src-tauri/target/release
      # TODO: code sign osx
      # - name: Install certificate (OSX)
      #   if: matrix.os == 'macos-latest'
      #   uses: apple-actions/import-codesign-certs@v1
      #   with:
      #     p12-file-base64: ${{ secrets.MACOS_CERTIFICATE }}
      #     p12-password: ${{ secrets.MACOS_CERTIFICATE_PWD }}
      # - name: Codesign executable (OSX)
      #   if: matrix.os == 'macos-latest'
      #   run: /usr/bin/codesign --force -s ${{ secrets.MAC_CODESIGN }} --options=runtime --entitlements app/osx_entitlements.xml --deep ${{ env.EXE_DIR }}/${{ matrix.exe_name }} -v
      # TODO: notorize osx
      # - name: Notarize app bundle (OSX)
      #   if: matrix.os == 'macos-latest'
      #   run: |
      #     cd ${{ env.EXE_DIR }}
      #     xcrun notarytool store-credentials "notarytool-profile" --apple-id "${{ secrets.APPLE_DEVELOPER_EMAIL }}" --team-id="${{ secrets.APPLE_TEAM_ID }}" --password "${{ secrets.APPLE_DEVELOPER_PASSWORD }}"
      #     xcrun notarytool submit "ambient-${{ matrix.target }}.zip" --keychain-profile "notarytool-profile" --wait
